spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          default_schema: security_db
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy
security:
  oauth2:
    client:
      client-id: zhang
      client-secret: zhang
      scope: all
      grant-type: authorization_code