// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/cn/zhang/proto/Calculator.proto

package cn.zhang.grpc;

public final class CalculatorOuterClass {
  private CalculatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$java/cn/zhang/proto/Calculator.proto\022\016" +
      "cn.zhang.proto\032\037java/cn/zhang/proto/Valu" +
      "e.proto2J\n\nCalculator\022<\n\ncalculator\022\025.cn" +
      ".zhang.proto.Value\032\025.cn.zhang.proto.Valu" +
      "e\"\000B\017\n\rcn.zhang.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.zhang.protoModel.ValueOuterClass.getDescriptor(),
        }, assigner);
    cn.zhang.protoModel.ValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
