// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Search.proto

package cn.zhang.grpc;

public final class SearchOuterClass {
  private SearchOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Search.proto\032\014Domain.proto\032\010Ip.proto2\242" +
      "\001\n\006Search\022\030\n\006search\022\007.Domain\032\003.IP\"\000\022&\n\022s" +
      "earchServerStream\022\007.Domain\032\003.IP\"\0000\001\022&\n\022s" +
      "earchClientStream\022\007.Domain\032\003.IP\"\000(\001\022.\n\030s" +
      "earchServerClientStream\022\007.Domain\032\003.IP\"\000(" +
      "\0010\001B\017\n\rcn.zhang.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.zhang.proto.DomainProto.getDescriptor(),
          cn.zhang.proto.IpProto.getDescriptor(),
        }, assigner);
    cn.zhang.proto.DomainProto.getDescriptor();
    cn.zhang.proto.IpProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
